openapi: 3.0.1
info:
  title: GATICKET-API
  description: API description in Markdown.
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/gaticket/'
tags:
  - name: users
  - name: devices
  - name: types
  - name: net
  - name: incidences
  - name: departments
paths:
  /users:
    get:
      tags:
        - users
      summary: Get all users on Data Base
      description: List of all users on Data Base
      operationId: getAllUsers
      responses:
        '200':
          description: Se devuelve un listado de todos los usuarios en la base de datos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Users'
              examples:
                User1:
                  $ref: '#/components/examples/User1'
    post:
      tags:
        - users
      summary: Add one user to data base
      description: Add one user
      operationId: postUser
      requestBody:
        $ref: '#/components/requestBodies/postUser'
      responses:
        '201':
          description: The new user it is add to the database
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
              examples:
                User1:
                  $ref: '#/components/examples/User1'

        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /users/{id}:
    parameters:
      - $ref: '#/components/parameters/id'
    get:
      tags:
        - users
      summary: Get user by Id
      description: Find a user by the id
      operationId: getUserById
      responses:
        '200':
          description: Se devuelve el usuario buscado por el Id
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Users'
              examples:
                User1:
                  $ref: '#/components/examples/User1'
        '404':
          $ref: '#/components/responses/NotFoundException'
        '500':
          $ref: '#/components/responses/InternalServerError'
    put:
      tags:
        - users
      summary: Update a user by Id
      description: Update a user by Id
      operationId: updateUserById
      requestBody:
        $ref: '#/components/requestBodies/postUser'
      responses:
        '202':
          description: Se acepta la modificacion completa y devuelve el cuerpo de la linea completo
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Accepted'
              examples:
                PutUser1:
                  $ref: '#/components/examples/User2'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFoundException'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      tags:
        - users
      summary: Delete a user, search by his Id
      description: Delete a user, search by his Id
      operationId: deleteUserById
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '404':
          $ref: '#/components/responses/NotFoundException'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /departments:
    get:
      tags:
        - departments
      summary: Get all departments on data base
      description: Get all departments on data base
      operationId: getAllDepartments
      responses:
        200:
          description: Se devuelve listado completo de los departamentos en la base de datos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Departments'
              examples:
                DepartmentList:
                  $ref: '#/components/examples/Department1'
        500:
          $ref: '#/components/responses/InternalServerError'
    post:
      tags:
        - departments
      summary: Add one department to data base
      operationId: AddDepartment
      requestBody:
        $ref: '#/components/requestBodies/postDepartment'
      responses:
        201:
          description: New department add to data base
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Departments'
              examples:
                Department1:
                  $ref: '#/components/examples/Department1'
        500:
          $ref: '#/components/responses/InternalServerError'
        400:
          $ref: '#/components/responses/BadRequest'
  /departments/{id}:
    parameters:
      - $ref: '#/components/parameters/id'
    get:
      tags:
        - departments
      summary: Get department on data base by Id
      description: Get department on data base by Id
      operationId: getDepartmentById
      responses:
        200:
          description: Se devuelve departamento buscado por el Id
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Departments'
              examples:
                DepartmentList:
                  $ref: '#/components/examples/Department1'
        500:
          $ref: '#/components/responses/InternalServerError'
    put:
      tags:
        - departments
      summary: Update a department by Id
      description: Update a department by Id
      operationId: updateDepartmentById
      requestBody:
        $ref: '#/components/requestBodies/postDepartment'
      responses:
        '202':
          description: Se acepta la modificacion completa y devuelve el cuerpo de la linea completo
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Accepted'
              examples:
                PutUser1:
                  $ref: '#/components/examples/Department2'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFoundException'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      tags:
        - departments
      summary: Erase a department by Id
      operationId: deleteDepartmentId
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '404':
          $ref: '#/components/responses/NotFoundException'
        '500':
          $ref: '#/components/responses/InternalServerError'



  /devices:
    get:
      tags:
        - devices
      summary: Get all devices on Data Base
      description: List of all devices on data base
      operationId: findAllDevices
      responses:
        '200':
          description: Se devuelve un listado con todos los dispositivos de la base de datos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Devices'
              examples:
                Line1:
                  $ref: '#/components/examples/AllDevices'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /devices/findByMac/{mac}:
    get:
      tags:
        - devices
      summary: Get device by mac
      description: Get devices typing his nic mac
      operationId: findDeviceByMac
      parameters:
        - $ref: '#/components/parameters/mac'
      responses:
        '200':
          description: Show a device search by the mac of his nic
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Devices'
              examples:
                Device:
                  $ref: '#/components/examples/Device1'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFoundException'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /devices/findBySerialNumber/{sn}:
    get:
      tags:
        - devices
      summary: Get device by Serial Number
      description: Ahow device with serial number
      operationId: findDevicesBySerialNumber
      parameters:
        - name: serial_number
          in: query
          description: Unique Idetification serial number
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Se devuelve los datos del dispositivo seleccionado por el cliente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Devices'
              examples:
                Device1:
                  $ref: '#/components/examples/Device1'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFoundException'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /device:
    post:
      tags:
        - devices
      description: "Add a new device to data base"
      operationId: addDevice
      requestBody:
        $ref: '#/components/requestBodies/postDevice'
      responses:
        '201':
          description: The new device it is add to the database
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Devices'
                examples:
                  example1:
                    $ref: '#/components/examples/Device1'

        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /device/{sn}:
    delete:
      tags:
        - devices
      description: Delete a device search by his serial number
      operationId: deleteDevice
      parameters:
        - $ref: '#/components/parameters/sn'
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '404':
          $ref: '#/components/responses/NotFoundException'
        '500':
          $ref: '#/components/responses/InternalServerError'
    put:
      parameters:
        - $ref: '#/components/parameters/sn'
      tags:
        - devices
      summary: Update one device search by serial number
      operationId: putDevicebySerialNumber
      requestBody:
        $ref: '#/components/requestBodies/postDevice'
      responses:
        '202':
          description: Se acepta la modificacion completa y devuelve el cuerpo completo del dispositivo
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Accepted'
              examples:
                PutDevice:
                  $ref: '#/components/examples/Device1'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFoundException'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  # Parametros que se usan mucho
  parameters:
    id:
      name: id
      in: path
      description: Id of a entity
      required: true
      schema:
        type: integer
        example: 2
    sn:
      name: sn
      in: path
      description: Serial Number
      required: true
      schema:
        type: string
        example: CZC6758B
    mac:
      name: mac
      in: path
      description: MAC of the device
      required: true
      schema:
        type: string
  # Ejemplos
  examples:
    Department1:
      summary: Ejemplo departamento
      value:
        departemtId: 1
        departmentName: Grocery,
        departmentPhone: 483-754-4078,
        departmentMail: Jameson.Huel73@yahoo.com,
        departmentCity: South Augustus
    Department2:
      summary: Ejemplo departamento
      value:
        departemtId: 1
        departmentName: Shoes,
        departmentPhone: 407-995-8626,
        departmentMail": Una.Dickens56@hotmail.com,
        departmentCity": Cormierside",
    User1:
      summary: Ejemplo usuario
      value:
        userId: 2
        userMail: pruebas@gmail.com
        userPassword: 11111
        userTip: B22222B
    User2:
      summary: Ejemplo usuario
      value:
        userId: 2
        userMail: modifcyuser@gmail.com
        userPassword: 22222
        userTip: F4567G
    Device1:
      summary: Ejemplo dispositivo
      value:
          deviceId: 23
          device_hd: 240
          device_ram: 32
          device_mac: '05:67:BF:65:AD'
          device_serial: 'FGH435T'
          device_model: 'HP ElitePro'
          device_datebuy: 12/04/2013
          device_datestart: 03/12/2013
    AllDevices:
      summary: Ejemplo array de dispositivos
      value:
        - deviceId: 23
          device_hd: 240
          device_ram: 32
          device_mac: '05:67:BF:65:AD'
          device_serial: 'FGH435T'
          device_model: 'HP ElitePro'
          device_datebuy: 12/04/2013
          device_datestart: 03/12/2013
        - deviceId: 243
          device_hd: 500
          device_ram: 16
          device_mac: '12:12:BF:65:E5'
          device_serial: 'CZC6757'
          device_model: 'Travel Mate'
          device_datebuy: 01/11/2020
          device_datestart: 30/09/2023


  schemas:
    Devices:
      type: object
      properties:
        deviceId:
          type: integer
          format: int64
          example: 12
        device_hd:
          type: integer
          format: int64
          example: 250
        device_ram:
          type: integer
          format: int64
          example: 16
        device_mac:
          type: string
          example: '84:32:34:CB:DF:45'
        device_serial:
          type: string
          example: 'KBC456CD'
        device_model:
          type: string
          example: 'EliteBook'
        device_datebuy:
          type: integer
          format: date
          example: 12/04/2013
        device_datestart:
          type: integer
          format: date
          example: 12/06/2014
    Net:
      type: object
      properties:
        netId:
          type: integer
          format: int64
          example: 4
        net:
          type: string
          example: '10.52.2.12'
    Departments:
      type: object
      properties:
        departmentId:
          type: integer
          format: int64
          example: 23
        department_name:
          type: string
          example: 'Apoyo Logistico'
        department_phone:
          type: string
          example: '07000148'
        department_mail:
          type: string
          format: email
          example: 'alogistico@gmail.com'
        department_city:
          type: string
          example: 'Barcelona'
    Users:
      type: object
      properties:
        userId:
          type: integer
          format: int64
          example: 45
        user_mail:
          type: string
          format: email
          example: 'pepito@gmail.com'
        user_password:
          type: string
          format: password
          example: '1234pepito'
        user_rol:
          type: string
          example: 'user'
    Incidences:
      type: object
      properties:
        incidenceId:
          type: integer
          format: int64
          example: 56
        incidence_status:
          type: boolean
          example: true
    Types:
      type: object
      properties:
        typeId:
          type: integer
          format: int64
          example: 43
        type:
          type: string
          example: 'Ordenador sobremesa'
    BadRequest:
      properties:
        errorCode:
          type: number
          format: int32
          example: 404
        message:
          type: string
          example: Bad Request
    NotFound:
      properties:
        errorCode:
          type: number
          format: int32
          example: 404
    ErrorResponse:
      properties:
        errorCode:
          type: number
          format: int32
          example: 500
        message:
          type: string
          example: Validation error

  responses:
    BadRequest:
      description: Solicitud realizada por el cliente no pudo ser procesada debido a un error en la solicitud. Esto podría deberse a una solicitud malformada, a la ausencia de información requerida en la solicitud o a una solicitud que no cumple con los requisitos del servidor.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequest'
          example:
            errorCode: 400
            message: 'Bad Request'
    NotFoundException:
      description: El servidor no pudo encontrar el recurso solicitado. Es decir, el servidor no puede encontrar la linea  que se está buscando.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotFound'
          example:
            errorCode: 404
            message: 'Object not found'
    InternalServerError:
      description: se ha producido un error interno en el servidor al procesar la solicitud del cliente
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            errorCode: 500
            message: "Internal server error"
    NoContent:
      description: Solicitud de eliminación se ha procesado correctamente, pero no hay contenido que devolver en la respuesta.
    Accepted:
      description: Modificacion aceptada correctamente
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Devices'

  requestBodies:
    postUser:
      description: Data from a new user
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Users'
    postDepartment:
      description: Datsa from a new department
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Departments'
    postDevice:
      description: Data for a new Device
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Devices'


